### ISSUE TITLE
Can't accept changes

### ISSUE THREAD

**Issue by klamping** [webdriverio/webdrivercss-adminpanel#21]
When I try and confirm a change, the image reverts back to the original. I also get the following response from the API:

`{"errno":34,"code":"ENOENT","path":"/path/to/webdrivercss-adminpanel/repositories/projectName/header.overview.new.png"}`

Maybe related to #15? I tried applying that code, the error went away, although I have to refresh the page to get the correct image.

**Comment by TheSavior** [comment]
It's because there is no `.new.png` anymore. It is `.baseline.png` and `.regression.png`. Apparently the code didn't get updated somewhere.

**Comment by klamping** [comment]
Just a note that #23 fixes this.

**Comment by christian-bromann** [comment]
Cool, then we can close this.
Thanks @klamping !!!

**Comment by klamping** [comment]
:+1:
